INSERT INTO `permissao` (`descricao`) VALUES
 ('REGRA_CADASTRAR_USUARIO'),
 ('REGRA_PESQUISAR_USUARIO'),
 ('REGRA_REMOVER_USUARIO'),
 ('REGRA_CADASTRAR_HISTORICO'),
 ('REGRA_PESQUISAR_HISTORICO'),
 ('REGRA_REMOVER_HISTORICO');